name: code-check

env:
  PGDATABASE: notused
  PGUSER: notused
  PGPASSWORD: notused
  PGPORT: notused
  BASE_URL: 0.0.0.0

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup
        run: make gitlab-setup

      - name: Code linter check
        run: make lint-code

      - name: Slim linter check
        run: make lint-slim

      - name: Tests
        run: make test